### ISSUE TITLE
Can't delete Hostname on Safari

### ISSUE THREAD

**Issue by YasserAntonio** [mageddo/dns-proxy-server#197]
### What is Happening

After adding a new hostname. I click on the red trash button.
A message in a red block state that hostname do not exist.
The hostname is still on the front end and in the config.json

### What is expected

I expect for the hostname to be delated on the front end and in the config.json

**Specs:**
- OS: Debian GNU/Linux 10 (buster)
- Docker Version: 19.03.4
- DPS Version: 2.19.0
- DPS Logs:
- Navigator : Safari 13.1

```
020-05-18T16:30:21.446312209Z 2020/05/18 16:30:21.445861 INFO f=index.go:75 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap.handle m=func1 m=/hostname/, status=begin, action=delete-hostname
2020-05-18T16:30:21.446505801Z 2020/05/18 16:30:21.446016 INFO f=index.go:75 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap.handle m=func1 m=/hostname/, status=parsed-host, action=delete-hostname, host={Id: Hostname: Ip:[0 0 0 0] Target: Ttl:0 Type: Env:}
2020-05-18T16:30:21.448290481Z 2020/05/18 16:30:21.447997 INFO f=localvo.go:231 pkg=github.com/mageddo/dns-proxy-server/events/local/localvo.(*Configuration) m=RemoveHostnameByEnvAndHostname status=begin, envName=, hostname=
2020-05-18T16:30:21.448900896Z 2020/05/18 16:30:21.448661 INFO f=index.go:75 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap.handle m=func1 m=/hostname/, status=error, action=delete-hostname, err=%!v(MISSING)
2020-05-18T16:30:21.449048239Z hostname not found
2020-05-18T16:30:21.449093291Z goroutine 588 [running]:
2020-05-18T16:30:21.449152717Z runtime/debug.Stack(0x115d4d0, 0x3cf7c1, 0x12)


```

**Comment by YasserAntonio** [comment]
Seems like the problem is isolated with Safari. I have no issue with google chrome. It must be a front end issue and it's exclusively related to the delete button with safari.

**Comment by mageddo** [comment]
Hey  @YasserAntonio , Sorry for the late answer, Finally I had access to a Mac computer and confirmed this bug at DPS version you reported, with safari Version 17.5 (19618.2.12.11.6).

It's fixed on my tests at the latest version of DPS 3.19, so I suggest you to upgrade DPS.

Thanks for your report.
