### ISSUE TITLE
Crash on startup; Does not work with systemd-resolved service

### ISSUE THREAD

**Issue by utdrmac** [mageddo/dns-proxy-server#246]
### What is Happening

* Crash on startup, following doc example
* Use systemd-resolved on Ubuntu 18.04 Bionic

### What is expected

For the container to work

### Steps to Reproduce

```
$ docker run --rm --hostname dns.mageddo --name dns-proxy-server -p 5380:5380   -v dns-proxy-server-conf:/app/conf   -v /var/run/docker.sock:/var/run/docker.sock   -v /etc:/host/etc   -e MG_RESOLVCONF=/host/etc/resolv.conf defreitas/dns-proxy-server
Unable to find image 'defreitas/dns-proxy-server:latest' locally
latest: Pulling from defreitas/dns-proxy-server
852e50cd189d: Pull complete
5abc811f0890: Pull complete
2bfbe129bfd9: Pull complete
Digest: sha256:707852462b31a3db86167a59ec5d203c78ac978a14dcd71c96b06bcdd5710344
Status: Downloaded newer image for defreitas/dns-proxy-server:latest
2022/07/24 03:01:40.305930 DEBUG f=local.go:29 pkg=github.com/mageddo/dns-proxy-server/events/local m=LoadConfiguration status=loading, path=/app/conf/config.json
2022/07/24 03:01:40.306052 DEBUG f=local.go:143 pkg=github.com/mageddo/dns-proxy-server/events/local m=storeToFile status=save, confPath=/app/conf/config.json
2022/07/24 03:01:40.306293 INFO f=local.go:160 pkg=github.com/mageddo/dns-proxy-server/events/local m=storeToFile status=success, confPath=/app/conf/config.json, time=0
2022/07/24 03:01:40.306328 INFO f=local.go:128 pkg=github.com/mageddo/dns-proxy-server/events/local m=storeDefaultConfig  status=success-creating-conf-file, path=%s /app/conf/config.json
2022/07/24 03:01:40.306338 DEBUG f=local.go:29 pkg=github.com/mageddo/dns-proxy-server/events/local m=LoadConfiguration status=loading, path=/app/conf/config.json
2022/07/24 03:01:40.306478 WARNING f=logging.go:120 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging m=SetLevel status=log-level-changed, log-level=6
2022/07/24 03:01:40.309233 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=GET /v1/caches
2022/07/24 03:01:40.309250 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=GET /v1/caches/size
2022/07/24 03:01:40.309261 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=GET /env/active
2022/07/24 03:01:40.309274 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=PUT /env/active
2022/07/24 03:01:40.309285 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=GET /env/
2022/07/24 03:01:40.309299 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=POST /env/
2022/07/24 03:01:40.309312 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=DELETE /env/
2022/07/24 03:01:40.309323 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=GET /hostname/
2022/07/24 03:01:40.309335 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=GET /hostname/find/
2022/07/24 03:01:40.309350 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=POST /hostname/
2022/07/24 03:01:40.309357 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=PUT /hostname/
2022/07/24 03:01:40.309369 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=DELETE /hostname/
2022/07/24 03:01:40.309379 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=GET /
2022/07/24 03:01:40.309422 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=GET /configuration/
2022/07/24 03:01:40.309438 INFO f=index.go:65 pkg=github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-httpmap m=handle status=registering, path=DELETE /network/disconnect-containers/
2022/07/24 03:01:40.309657 WARNING f=dns.go:160 pkg=main m=main server started
2022/07/24 03:01:40.309946 INFO f=asm_amd64.s:1338 pkg=runtime m=goexit uuid=4fe5377376 status=setup-default-dns, setup-dns=true
2022/07/24 03:01:40.310202 INFO f=dns.go:87 pkg=main m=serve status=begin, port=53
2022/07/24 03:01:40.310249 INFO f=dns.go:87 pkg=main m=serve status=begin, port=53
2022/07/24 03:01:40.310273 INFO f=asm_amd64.s:1338 pkg=runtime m=goexit status=web-server-starting, port=5380
2022/07/24 03:01:40.310398 ERROR f=asm_amd64.s:1338 pkg=runtime m=goexit  status=cant-turn-default-dns
open /host/etc/resolv.conf: no such file or directory
goroutine 25 [running]:
runtime/debug.Stack(0xc00031c480, 0xc0001f3c00, 0x35)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging.transformErrorInStackTrace(0xc000223de0, 0x2, 0x2, 0x0, 0x203000, 0xd, 0x2)
	/app/src/github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging/nativelogger.go:72 +0x10c
github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging.(*defaultLogger).print(0xc0000a04e0, 0xc000223de0, 0x2, 0x2, 0x3)
	/app/src/github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging/nativelogger.go:92 +0x63
github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging.(*defaultLogger).Error(0xc0000a04e0, 0xc000223de0, 0x2, 0x2)
	/app/src/github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging/nativelogger.go:49 +0x52
github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging.Error(0xc000223de0, 0x2, 0x2)
	/app/src/github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging/logging.go:91 +0x7e
main.main.func2()
	/app/src/github.com/mageddo/dns-proxy-server/dns.go:151 +0x1af
created by main.main
	/app/src/github.com/mageddo/dns-proxy-server/dns.go:145 +0x1c0

2022/07/24 03:01:40.310413 ERROR f=exitcodes.go:19 pkg=github.com/mageddo/dns-proxy-server/utils/exitcodes m=Exit status=exiting, code=1
2022/07/24 03:01:40.310425 INFO f=exitcodes.go:21 pkg=github.com/mageddo/dns-proxy-server/utils/exitcodes m=Exit  status=msg-posted
2022/07/24 03:01:40.310452 WARNING f=dns.go:162 pkg=main m=main status=exiting ;) signal=hangup
2022/07/24 03:01:40.310472 INFO f=resolvconf.go:23 pkg=github.com/mageddo/dns-proxy-server/resolvconf m=RestoreResolvconfToDefault status=begin
2022/07/24 03:01:40.310540 INFO f=resolvconf.go:26 pkg=github.com/mageddo/dns-proxy-server/resolvconf m=RestoreResolvconfToDefault status=success, err=%!v(MISSING)
open /host/etc/resolv.conf: no such file or directory
goroutine 1 [running]:
runtime/debug.Stack(0xc00031c4e0, 0xc0001f3f80, 0x35)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging.transformErrorInStackTrace(0xc000320750, 0x1, 0x1, 0xc0001eddd0, 0x0, 0x0, 0x0)
	/app/src/github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging/nativelogger.go:72 +0x10c
github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging.(*defaultLogger).fPrint(0xc0000a04e0, 0x875967, 0x16, 0xc000320750, 0x1, 0x1, 0x6)
	/app/src/github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging/nativelogger.go:87 +0x144
github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging.(*defaultLogger).Infof(0xc0000a04e0, 0x875967, 0x16, 0xc000320750, 0x1, 0x1)
	/app/src/github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging/nativelogger.go:37 +0x66
github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging.Infof(0x875967, 0x16, 0xc000320750, 0x1, 0x1)
	/app/src/github.com/mageddo/dns-proxy-server/vendor/github.com/mageddo/go-logging/logging.go:73 +0x96
github.com/mageddo/dns-proxy-server/resolvconf.RestoreResolvconfToDefault(0x877ee2, 0x1b)
	/app/src/github.com/mageddo/dns-proxy-server/resolvconf/resolvconf.go:25 +0xf1
main.main()
	/app/src/github.com/mageddo/dns-proxy-server/dns.go:162 +0x29f
```

**Specs:**
- OS: Ubuntu 18.04 LTS
- Docker Version: 20.10.17
- DPS Version: Current :latest

**Comment by utdrmac** [comment]
```
$ ls -la /etc/resolv.conf
lrwxrwxrwx 1 root root 39 Feb 14  2019 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
```

**Comment by mageddo** [comment]
Got it, /etc/resolv.conf is a symbolic link, as you are creating a volume for the  directory, the symlink won't solve inside the container.

The standard run as proposed at the docs will work, tough:

```bash
$ docker run -v /etc/resolv.conf:/etc/resolv.conf \
-v /var/run/docker.sock:/var/run/docker.sock \
--rm defreitas/dns-proxy-server:2.19.0
```

Anyway, people proposed a different approach to configure DPS to linux hosts in #248 , I will take a look to consider it for a new feature.


For this specific issue usecase  I think there's no much more to do.
