### ISSUE TITLE
v3 regression: Wild card domain resolution appears to fail unlike in v2

### ISSUE THREAD

**Issue by addshore** [mageddo/dns-proxy-server#309]
### What is Happening

I am trying on the v3 betas in https://gitlab.wikimedia.org/repos/releng/cli/-/merge_requests/330
This drops right in the place of my usage of v2 without any additional changes https://gitlab.wikimedia.org/repos/releng/cli/-/merge_requests/330/diffs#d632a42138acb9bcc35a4d2e3eee040758ab84cc_6_6
And one of my end to end tests is failing https://gitlab.wikimedia.org/repos/releng/cli/-/jobs/69627

Specifically....
A [dps service](https://gitlab.wikimedia.org/repos/releng/cli/-/blob/03104cb9fd8d45403f10e70c5d4b09de694ee168/internal/mwdd/files/embed/base.yml#L6) is created in a docker-compose setup with [a fixed IP on a `dps` network](https://gitlab.wikimedia.org/repos/releng/cli/-/blob/03104cb9fd8d45403f10e70c5d4b09de694ee168/internal/mwdd/files/embed/base.yml#L12) and [with access to the docker socket ](https://gitlab.wikimedia.org/repos/releng/cli/-/blob/03104cb9fd8d45403f10e70c5d4b09de694ee168/internal/mwdd/files/embed/base.yml#L9)
This DNS service is then used by all the contianer in the setup, [such as `mediawiki-fresh`](https://gitlab.wikimedia.org/repos/releng/cli/-/blob/03104cb9fd8d45403f10e70c5d4b09de694ee168/internal/mwdd/files/embed/mediawiki-fresh.yml#L8) which [specifies the dns service by its IP](https://gitlab.wikimedia.org/repos/releng/cli/-/blob/03104cb9fd8d45403f10e70c5d4b09de694ee168/internal/mwdd/files/embed/mediawiki-fresh.yml#L17)
As part of the test this service tries to resolve `default.mediawiki.mwdd`, but it [fails](https://gitlab.wikimedia.org/repos/releng/cli/-/jobs/69627#L551)

```
[0-0] Error in "Page."before all" hook for "should be previewable @daily""
Error: getaddrinfo ENOTFOUND default.mediawiki.mwdd
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[0-0] RETRYING in chrome - /tests/selenium/specs/page.js
[0-0] RUNNING in chrome - /tests/selenium/specs/page.js
[0-0] Error in "Page."before all" hook for "should be previewable @daily""
Error: getaddrinfo ENOTFOUND default.mediawiki.mwdd
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[0-0] FAILED in chrome - /tests/selenium/specs/page.js (1 retries)
```

The host is [correctly resolved outside of a container](https://gitlab.wikimedia.org/repos/releng/cli/-/jobs/69627#L457), but when inside it appears to struggle or fail?
(Though this is perhaps due to the fact I use *.localhost)?

The service that should be resolved to is `mediawiki-web`, [where a `VIRTUAL_HOST` env var is used.](https://gitlab.wikimedia.org/repos/releng/cli/-/blob/03104cb9fd8d45403f10e70c5d4b09de694ee168/internal/mwdd/files/embed/mediawiki.yml#L40)

### What is expected

A container that uses DPS as the DNS server should be able to resolve this wild card hostname.

**Comment by mageddo** [comment]
Wildcards were supposed to be working, I will do some tests

**Comment by mageddo** [comment]
Found the cause 

>  Docker container wasn't solving from env when the names weren't separated by ` , ` (spaces before and after the comma were needed)

**Comment by mageddo** [comment]
Minimal reproducible example: https://github.com/mageddo/dns-proxy-server/tree/c1dcfe5/examples/wildcards

**Comment by mageddo** [comment]
Github automatically closed the issue, please reopen if the issue persists

**Comment by addshore** [comment]
It looks like I can confirm that wildcards are now working in my e2e tests using the latest beta.
There is another issue, I'll investigate and try to write a ticket if I figure out what is up.
