### ISSUE TITLE
Permanent error on AAAA request

### ISSUE THREAD

**Issue by pavlyuts** [mageddo/dns-proxy-server#428]
### What is Happening / What is expected
DPS logs fault, associated to AAAA request on container name
Log entry:
```
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]: 08:28:44.878 [Thread-41      ] WAR c.m.d.server.dns.RequestHandlerDefault            l=93   m=solve0                          status=solverFailed, currentSolverTime=8, totalTime=8, solver=SolverDocker, query=query=AAAA:db.docker, eClass=NullPointerException, msg=null
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]: java.lang.NullPointerException: null
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.Objects.requireNonNull(Objects.java:233)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.Optional.of(Optional.java:113)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.docker.ContainerSolvingService.findBestMatch(ContainerSolvingService.java:50)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.solver.SolverDocker.lambda$handle$0(SolverDocker.java:40)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.solver.HostnameMatcher.match(HostnameMatcher.java:22)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.solver.SolverDocker.handle(SolverDocker.java:39)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.RequestHandlerDefault.solve0(RequestHandlerDefault.java:75)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.solver.SolverCache.lambda$handleRes$0(SolverCache.java:38)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.commons.caching.LruTTLCache.lambda$computeIfAbsentWithTTL$1(LruTTLCache.java:94)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.commons.caching.LruTTLCache.lambda$computeIfAbsentWithTTL$2(LruTTLCache.java:88)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.commons.caching.LruTTLCache.computeIfAbsentWithTTL(LruTTLCache.java:86)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.solver.SolverCache.handleRes(SolverCache.java:36)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.solver.SolverCache.handle(SolverCache.java:31)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.RequestHandlerDefault.solve(RequestHandlerDefault.java:51)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.RequestHandlerDefault.handle(RequestHandlerDefault.java:42)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.UDPServer.handle(UDPServer.java:54)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at com.mageddo.dnsproxyserver.server.dns.UDPServer.lambda$start0$0(UDPServer.java:42)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at java.base@19.0.2/java.lang.Thread.run(Thread.java:1589)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
Dec 07 11:28:44 pavlyuts.ru dns-proxy-server[448]:         at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```
To reproduce:
1. Setup Docker
2.  Setup DPS standaone mode and configure it
3. Create container with docker default network conection and name 'test'
4. `dig @127.0.0.1 test.docker AAAA`
5. Check DPS logs

DPS config file
```
{
  "version": 2,
  "remoteDnsServers": [ ],
  "envs": [
    {
      "name": "",
      "hostnames": [ ]
    }
  ],
  "activeEnv": "",
  "webServerPort": 5380,
  "dnsServerPort": 53,
  "logLevel": "INFO",
  "logFile": "console",
  "registerContainerNames": true,
  "domain": "docker",
  "dpsNetwork": false,
  "dpsNetworkAutoConnect": false,
  "defaultDns": false,
  "hostMachineHostname" : "host.docker",
  "serverProtocol": "UDP_TCP",
  "dockerHost": null,
  "resolvConfOverrideNameServers": false,
  "noRemoteServers": true,
  "noEntriesResponseCode": 3
}

```
### Specs
* OS: Debian 11, Oracle Linux 8 
* Docker Version: 24.0.7
* DPS Version: 3.15.13-snapshot

**Comment by sneusse** [comment]
same here, can we disable AAAA in some way?

**Comment by mageddo** [comment]
Hey thanks for the report.

I got this, the issue is caused when beyond the container, your hostmachine or the docker engine also hasn't an associated IPV6, it will try to use the host machine IPV6 but it hasn't one associated, null is returned:

```
ContainerSolvingService l=132 ...  status=noNetworkAvailable, usingHostMachineIp=null
```

Then the error occurs

```
18:23:47.453 [Thread-6       ] WAR c.m.d.server.dns.RequestHandlerDefault            l=93   m=solve0                          status=solverFailed, currentSolverTime=33, totalTime=33, solver=SolverDocker, query=query=AAAA:test.docker, eClass=NullPointerException, msg=null
java.lang.NullPointerException: null
        at java.base@19.0.2/java.util.Objects.requireNonNull(Objects.java:233)
        at java.base@19.0.2/java.util.Optional.of(Optional.java:113)
        at java.base@19.0.2/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194)
        at java.base@19.0.2/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191)
        at java.base@19.0.2/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base@19.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@19.0.2/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at com.mageddo.dnsproxyserver.docker.ContainerSolvingService.findBestMatch(ContainerSolvingService.java:50)
```

The bug is here, `.elseGet` will throw a NPE when null is returned, which is the case.

https://github.com/mageddo/dns-proxy-server/blob/17b0c0043d883cf9f902075739183c7938c808b2/src/main/java/com/mageddo/dnsproxyserver/docker/ContainerSolvingService.java#L127-L135


I'm working on the fix

**Comment by mageddo** [comment]
> same here, can we disable AAAA in some way?

No sure, it's related to your OS and DNS client, it's asking for AAAA records then DPS will answer them, so you have to disable the AAAA queries on the requester, don't know how.

**Comment by mageddo** [comment]
Just to make it clear, this issue won't make DPS stop of working, just will produce a lot of unnecessary logs

**Comment by mageddo** [comment]
Version was released, you can reopen if the issue persists somehow
